version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  build-and-push:
    environment:
      DOCKER_IMAGE: quanghuy2601/my-app
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8e:1b:73:6c:f8:95:67:f3:a8:fd:a7:ff:00:5c:19:b0"
      - run: ssh -o StrictHostKeyChecking=no -v ubuntu@ec2-13-211-134-8.ap-southeast-2.compute.amazonaws.com "./deploy.sh"

workflows:
  my-pipeline:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build-and-push
